version: '3'
services:
  db:
    build:
      context: .
      dockerfile: /docker/db/Dockerfile 
    environment:
      - MYSQL_DATABASE=management
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306    
   
  web:
    build:
      context: .
      dockerfile: /docker/web/Dockerfile 
    restart: on-failure 
    ports:
      - 8080:8080
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/management?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root   
